**Python library is a collection of functions and methods that allows you to perform many actions without writing your code**

# Python Numpy
NumPy stands for Numerical python and is the core library for numeric and scientific computing.
It consists if multi-dimensional array objects and a collection of routines for processing those arrays

In [24]:
#Single-dimensional Array

import numpy as np

n1=np.array([10,20,30,40])
print (n1)

print (type(n1))

#Multi-dimensional Array

n2=np.array([[10,20,30,40],[40,30,20,10]])
print (n2)

[10 20 30 40]
<class 'numpy.ndarray'>
[[10 20 30 40]
 [40 30 20 10]]


In [25]:
#initializing NumPy array with zeros


n1=np.zeros((1,2))
print (n1)

print ("space")

n1=np.zeros((5,5))
print (n1)

[[0. 0.]]
space
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [19]:
#Initializing NumPy array with same number 


n1=np.full((2,2),10)
print(n1)

[[10 10]
 [10 10]]


In [26]:
#Initializing NumPy array within a range


n1=np.arange(10,20)                        #aranging numbers between 10 to 10
print(n1)

print('space')

n1=np.arange(10,50,5)                     #arranging numbers between 10 to 50 with the difference of 5
print(n1)

[10 11 12 13 14 15 16 17 18 19]
space
[10 15 20 25 30 35 40 45]


In [27]:
#Initializing NumPy array with random numbers

n1=np.random.randint(1,100,5)
print (n1)

[18 32 95  9 19]


In [28]:
#checkin the shape of Numpy arrays

n1=np.array([[1,2,3],[4,5,6]])
print (n1.shape)

print ('space')

n1.shape = (3,2)
print (n1.shape) 

(2, 3)
space
(3, 2)


# Joining NumPy Arrays

In [30]:
#vstack()       vertical stack

n1=np.array([10,20,30])
n2=np.array([40,50,60])

print (np.vstack((n1,n2)))

#hstack()       horizontal stack
print("space")

print (np.hstack((n1,n2)))

#column_stack()
print("space")

np.column_stack((n1,n2))

[[10 20 30]
 [40 50 60]]
space
[10 20 30 40 50 60]
space


array([[10, 40],
       [20, 50],
       [30, 60]])

# Numpy Intersection and Difference

In [5]:
n1=np.array([10,20,30,40,50,60])
n2=np.array([50,60,70,80,90])

print (np.intersect1d(n1,n2))                   #intersection
print (np.setdiff1d(n1,n2))                     #difference
print (np.setdiff1d(n2,n1))

[50 60]
[10 20 30 40]
[70 80 90]


# Numpy array mathematics

In [7]:
#additin of NumPy arrays

n1=np.array([10,20])
n2=np.array([30,40])

print (np.sum([n1,n2]))
print (np.sum([n1,n2],axis=0))    
print (np.sum([n1,n2],axis=1))

100
[40 60]
[30 70]


In [8]:
#basic addition

n1=np.array([10,20,30])
n1=n1+1
print(n1)

[11 21 31]


In [9]:
#basic multiplication 

n1=np.array([10,20,30])
n1=n1*2
n1

array([20, 40, 60])

In [11]:
#basic subtraction

n1=np.array([10,20,30])
n1=n1-1
n1

array([ 9, 19, 29])

In [12]:
#basic division

n1=np.array([10,20,30])
n1=n1/2
n1

array([ 5., 10., 15.])

# NumPy math functions

In [15]:
n1=np.array([10,20,30,40,50,60])       #mean
print (np.mean(n1))

n1=np.array([1,3,45,343,53])           #standard deviation
print (np.std(n1))

n1=np.array([11,44,5,96,67,85])        #median
np.median(n1)

35.0
128.75402906317146


55.5

# Numpy save and load 

In [17]:
#saving NumPy array

n1=np.array([10,20,30,40,50,60])
np.save('my_numpy', n1)

In [18]:
#loading the array

n2=np.load('my_numpy.npy')
n2

array([10, 20, 30, 40, 50, 60])

# Python Pandas

Pandas stands for panel data and is the core library for data manipulation and data analysis. It consists of single and multi-dimensional data structures for data manipulation. we have single-dimensional and multi dimensional data structures in numpy, but in pandas we have **series object** and **data frame**. they are basically the same thing with different names. 


In [34]:
#Series object - its one dimentional labeled array

s1=pd.Series([1,2,3,4,5])                                    #series object
print (s1)
print (type(s1))                                             #type

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>


In [32]:
s1=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])        #changing index
print (s1)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [33]:
#You can also create a series object from a dictionary!!!

s1=pd.Series({'a':10,'b':20,'c':30})
print (s1)

a    10
b    20
c    30
dtype: int64


In [35]:
#Changing index position

s1=pd.Series({'a':10,'b':20,'c':30},index=['b','c','d','a'])
print (s1)

b    20.0
c    30.0
d     NaN
a    10.0
dtype: float64


In [39]:
#extracting individual elements and basic math operations on series

s1=pd.Series([1,2,3,4,5,6,7,8,9])
print (s1[3])                                   #extracting a single element
print('space')
print (s1[-3:])                                 #extracting a sequence of elements
print('space')
print (s1[:4])                                  #extracting elements from back
print('space')
print (s1+5)                                    #adding a scalar value to Series elments 
print('space')
s1=pd.Series([1,2,3,4,5,6,7,8,9])               #adding two series objects
s2=pd.Series([10,20,30,40,50,60,70,80,90])
print (s1+s2)


4
space
6    7
7    8
8    9
dtype: int64
space
0    1
1    2
2    3
3    4
dtype: int64
space
0     6
1     7
2     8
3     9
4    10
5    11
6    12
7    13
8    14
dtype: int64
space
0    11
1    22
2    33
3    44
4    55
5    66
6    77
7    88
8    99
dtype: int64


In [3]:
#Pandas dataframe - Dataframe is a 2-dimensional labelled data-structre. a data frame comprises of rows and columns

import pandas as pd

pd.DataFrame({"Name":['Bob','Sam','Anne'],"Marks":[76,25,92]})

Name  Marks
0   Bob     76
1   Sam     25
2  Anne     92

In [7]:
#Dataframe in Built function

import pandas as pd 

iris=pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data')

In [8]:
iris.head()

5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [9]:
iris.tail()

5.1  3.5  1.4  0.2     Iris-setosa
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

In [11]:
iris.shape

(149, 5)

In [12]:
iris.describe()

5.1         3.5         1.4         0.2
count  149.000000  149.000000  149.000000  149.000000
mean     5.848322    3.051007    3.774497    1.205369
std      0.828594    0.433499    1.759651    0.761292
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.400000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [13]:
iris.iloc[0:3,0:2]               #for extracting first 3 rows and first 2 columns 

5.1  3.5
0  4.9  3.0
1  4.7  3.2
2  4.6  3.1

In [14]:
iris.iloc[5:11,2:]              #for extracting all the rows after 5 and all the cloumns after 3.5

1.4  0.2  Iris-setosa
5   1.4  0.3  Iris-setosa
6   1.5  0.2  Iris-setosa
7   1.4  0.2  Iris-setosa
8   1.5  0.1  Iris-setosa
9   1.5  0.2  Iris-setosa
10  1.6  0.2  Iris-setosa

**.iloc and .loc**

we give **column index** in .iloc and in .loc, we give **column's name** 

In [16]:
iris.loc[0:3,("5.1","3.5")]

5.1  3.5
0  4.9  3.0
1  4.7  3.2
2  4.6  3.1
3  5.0  3.6

In [17]:
#Dropping columns

iris.drop('5.1',axis=1)                 #dropping the first column 

3.5  1.4  0.2     Iris-setosa
0    3.0  1.4  0.2     Iris-setosa
1    3.2  1.3  0.2     Iris-setosa
2    3.1  1.5  0.2     Iris-setosa
3    3.6  1.4  0.2     Iris-setosa
4    3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...             ...
144  3.0  5.2  2.3  Iris-virginica
145  2.5  5.0  1.9  Iris-virginica
146  3.0  5.2  2.0  Iris-virginica
147  3.4  5.4  2.3  Iris-virginica
148  3.0  5.1  1.8  Iris-virginica

[149 rows x 4 columns]

In [18]:
#Dropping rows

iris.drop([1,2,3],axis=0)              #dropping 2nd,3rd, and 4th row 

5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
5    4.6  3.4  1.4  0.3     Iris-setosa
6    5.0  3.4  1.5  0.2     Iris-setosa
7    4.4  2.9  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[146 rows x 5 columns]

In [22]:
print (iris.mean())                  #to find the mean of the date

5.1    5.848322
3.5    3.051007
1.4    3.774497
0.2    1.205369
dtype: float64


In [23]:
print (iris.median())                #to find the median of the data


5.1    5.8
3.5    3.0
1.4    4.4
0.2    1.3
dtype: float64


In [24]:
print (iris.min())                  #for find the minimum value of the data

5.1                    4.3
3.5                    2.0
1.4                    1.0
0.2                    0.1
Iris-setosa    Iris-setosa
dtype: object


In [25]:
print (iris.max())                  #for find the maximum value of the data

5.1                       7.9
3.5                       4.4
1.4                       6.9
0.2                       2.5
Iris-setosa    Iris-virginica
dtype: object


**apply method**

In [27]:
#for reducing the 2st column and 4th column by half, we can use apply method 

def half(s):
    return s*0.5

iris[['5.1','1.4']].apply(half)

5.1   1.4
0    2.45  0.70
1    2.35  0.65
2    2.30  0.75
3    2.50  0.70
4    2.70  0.85
..    ...   ...
144  3.35  2.60
145  3.15  2.50
146  3.25  2.60
147  3.10  2.70
148  2.95  2.55

[149 rows x 2 columns]

In [28]:
#for multiplying 2st column and 4th column by 2, we can use apply method too

def half(s):
    return s*2

iris[['5.1','1.4']].apply(half)

5.1   1.4
0     9.8   2.8
1     9.4   2.6
2     9.2   3.0
3    10.0   2.8
4    10.8   3.4
..    ...   ...
144  13.4  10.4
145  12.6  10.0
146  13.0  10.4
147  12.4  10.8
148  11.8  10.2

[149 rows x 2 columns]

In [29]:
iris['Iris-setosa'].value_counts()        #to find out how many different categorical values are present in 'Iris-setosa' coulmn

Iris-virginica     50
Iris-versicolor    50
Iris-setosa        49
Name: Iris-setosa, dtype: int64

In [30]:
iris.sort_values(by='5.1')                #for arranging all the categorical column in ascending oder(sorting)

5.1  3.5  1.4  0.2     Iris-setosa
12   4.3  3.0  1.1  0.1     Iris-setosa
41   4.4  3.2  1.3  0.2     Iris-setosa
37   4.4  3.0  1.3  0.2     Iris-setosa
7    4.4  2.9  1.4  0.2     Iris-setosa
40   4.5  2.3  1.3  0.3     Iris-setosa
..   ...  ...  ...  ...             ...
117  7.7  2.6  6.9  2.3  Iris-virginica
116  7.7  3.8  6.7  2.2  Iris-virginica
121  7.7  2.8  6.7  2.0  Iris-virginica
134  7.7  3.0  6.1  2.3  Iris-virginica
130  7.9  3.8  6.4  2.0  Iris-virginica

[149 rows x 5 columns]